# Generated by Django 3.1.3 on 2021-02-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210222_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('rc_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration Number')),
            ],
        ),
        migrations.AddField(
            model_name='corttsaccount',
            name='open_balance',
            field=models.FloatField(default=0.0, verbose_name='Opening Balance'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='account.corttsaccount', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='corttsaccount',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='account.company', verbose_name='Company'),
        ),
    ]
