# Generated by Django 3.1.3 on 2021-02-25 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210222_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_balance', models.FloatField(default=0.0, verbose_name='Opening Balance')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created At')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name_plural': 'Expense Accounts',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at', '-last_modified']},
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_ups', to='account.expenseaccount', verbose_name='Account')),
            ],
        ),
    ]
