# Generated by Django 3.1.3 on 2021-02-27 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210225_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='corttsaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='corttsaccount',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='expenseaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='expenseaccount',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='otheraccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='otheraccount',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified'),
        ),
    ]
