version: "3.9"
   
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  db:
    image: postgres
    environment:
      - POSTGRES_DB=management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/management
    ports:
      - "8000:8000"
      - "4000:4000"
    depends_on:
      - db
      - redis