# Generated by Django 3.1.3 on 2021-02-26 15:18

import apartments.models.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.CharField(max_length=50, verbose_name='Flat')),
                ('building', models.CharField(max_length=255, verbose_name='Building')),
                ('address', models.CharField(max_length=50, verbose_name='')),
                ('area', models.CharField(choices=[('Lekki', 'Lekki'), ('Ikoyi', 'Ikoyi'), ('Victoria Island', 'Victoria Island'), ('Oniru', 'Oniru')], max_length=50, verbose_name='Model')),
                ('rent', models.FloatField(verbose_name='Rent')),
                ('service_charge', models.FloatField(default=0.0, verbose_name='Service Charge')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Occupied?')),
                ('other_info', models.TextField(verbose_name='Other Information')),
                ('no_of_bed', models.IntegerField(verbose_name='Number of Bedrooms')),
                ('no_of_bath', models.IntegerField(verbose_name='Number of Bathrooms')),
                ('no_of_toilet', models.IntegerField(verbose_name='Number of Toilets')),
                ('no_of_park', models.IntegerField(verbose_name='Number of Car Park')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='Furnished?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Created_at')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='contacts.client', verbose_name='Landlord')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupying', to='contacts.client', verbose_name='Tenant')),
            ],
            options={
                'ordering': ['flat'],
            },
        ),
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Start')),
                ('end', models.DateTimeField(default=apartments.models.models.return_date_time, verbose_name='End')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Created_at')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment', verbose_name='Apartment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.client', verbose_name='Tenant')),
            ],
            options={
                'verbose_name_plural': 'Tenancy Periods',
                'ordering': ['-start'],
            },
        ),
    ]
