# Generated by Django 3.1.3 on 2021-02-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(max_length=50, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.CharField(choices=[('Lekki', 'Lekki'), ('Ikoyi', 'Ikoyi'), ('Victoria Island', 'Victoria Island'), ('Oniru', 'Oniru')], max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='other_info',
            field=models.TextField(blank=True, null=True, verbose_name='Other Information'),
        ),
    ]
