# Generated by Django 3.1.3 on 2021-03-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_auto_20210227_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='no_of_bath',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Bathrooms'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='no_of_park',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Car Park'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='no_of_toilet',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Toilets'),
        ),
    ]
