# Generated by Django 3.1.3 on 2021-03-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_auto_20210301_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Amount Paid'),
            preserve_default=False,
        ),
    ]
