# Generated by Django 3.1.3 on 2021-03-03 11:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_auto_20210301_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255, verbose_name='Body')),
                ('sent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Sent')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment', verbose_name='Apartment')),
            ],
        ),
    ]
