# Generated by Django 3.1.3 on 2021-03-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='sent',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Sent'),
        ),
    ]
