# Generated by Django 3.1.3 on 2021-03-05 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='doc_type',
            field=models.CharField(choices=[('word', 'word'), ('pdf', 'pdf')], default='pdf', max_length=50, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartments.apartment', verbose_name='Apartment'),
        ),
    ]
