# Generated by Django 3.1.3 on 2021-02-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_and_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
