# Generated by Django 3.1.3 on 2021-02-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_and_expenses', '0002_auto_20210226_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='pay_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Transfer', 'Transfer')], default='Cash', max_length=50, verbose_name='Pay Method'),
        ),
    ]
